# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 35a768967f2bc99d21de792e5b47ffe39c04948e9ba2918aa47262406fd052b1c3daefffc4fc948ca8778104abe7e4e81a5d9c4fa027dd9d8062e9603835c405

test:
  secret_key_base: 83e6376881dbaeda7b64f92c991e6cb5a921a98d21d96a85d77f8de14ec6e7c33eaca609e282bacf84b50175adebbfc73bf3be8e3df1e9ba63b4c9257f956b60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
